<?php

use Database\traits\TruncateTable;
use Database\traits\DisableForeignKeys;

use Illuminate\Database\Seeder;
use Carbon\Carbon as Carbon;
use Illuminate\Support\Facades\DB;

/**
 * @author Cesar Augusto Verduzco Reyna <cesar.skyous@gmail.com> Alias Skyous
 * Class CountriesTableSeeder extends Seeder
 * Description: Create all the data into the data base of countries with code country ISO Alpha-2
 * Date 04/09/2019
 * @method run
 */
class CountriesTableSeeder extends Seeder
{
    use DisableForeignKeys,TruncateTable;
    /**
     * Run the database seeds. Method to insert all the default data of countries
     *
     * @return void
     */
    public function run()
    {
        $this->disableForeignKeys();
        $this->truncate('countries');
        $countries = [
          //Countries with A
          [
            'country_name' =>'Afghanistan',
            'country_code' => 'AF',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Aland Islands',
            'country_code' => 'AX',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Albania',
            'country_code' => 'AL',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Algeria',
            'country_code' => 'DZ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'America Samoa',
            'country_code' => 'AS',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Andorra',
            'country_code' => 'AD',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Angola',
            'country_code' => 'AO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Anguilla',
            'country_code' => 'AI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Antigua and Barbuda',
            'country_code' => 'AG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Argentina',
            'country_code' => 'AR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Armenia',
            'country_code' => 'AM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Aruba',
            'country_code' => 'AW',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Australia',
            'country_code' => 'AU',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Austria',
            'country_code' => 'AT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Azerbaijan',
            'country_code' => 'AZ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //Countries with B
          [
            'country_name' =>'Bahamas',
            'country_code' => 'BS',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Bahrain',
            'country_code' => 'BH',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Bangladesh',
            'country_code' => 'BD',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Barbados',
            'country_code' => 'BB',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Belarus',
            'country_code' => 'BY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Belguim',
            'country_code' => 'BE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Belize',
            'country_code' => 'BZ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Benin',
            'country_code' => 'BJ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Bermuda',
            'country_code' => 'BM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Bhutan',
            'country_code' => 'BT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Bolivia',
            'country_code' => 'BO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Bosnia and Herzegovina',
            'country_code' => 'BA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Botswana',
            'country_code' => 'BW',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Bouvet Islan',
            'country_code' => 'BV',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Brazil',
            'country_code' => 'BR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'British Virgin Islands',
            'country_code' => 'VG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'British Indian Ocean Territory',
            'country_code' => 'IO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Brunei Darussalam',
            'country_code' => 'BN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Bulgaria',
            'country_code' => 'BG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Burkina Faso',
            'country_code' => 'BF',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Burundi',
            'country_code' => 'BI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //Countries with C
          [
            'country_name' =>'Cambodia',
            'country_code' => 'KH',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Camerron',
            'country_code' => 'CM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Canada',
            'country_code' => 'CA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Cape Verde',
            'country_code' => 'CV',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Cayman Islands',
            'country_code' => 'KY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Central African Republic',
            'country_code' => 'CF',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Chile',
            'country_code' => 'CL',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'China',
            'country_code' => 'CN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Hong Kong',
            'country_code' => 'HK',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Macao',
            'country_code' => 'MO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Colombia',
            'country_code' => 'CO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],[
            'country_name' =>'Comoros',
            'country_code' => 'KM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Republic of the Congo',
            'country_code' => 'CG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Democratic Republic of the Congo',
            'country_code' => 'CD',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Cook Islands',
            'country_code' => 'CK',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Costa Rica',
            'country_code' => 'CR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Ivory Coast',
            'country_code' => 'CI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Croatia',
            'country_code' => 'HR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Cuba',
            'country_code' => 'CU',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Cyprus',
            'country_code' => 'CY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Czech Republic',
            'country_code' => 'CZ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with D
          [
            'country_name' =>'Denmark',
            'country_code' => 'DK',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Djibouti',
            'country_code' => 'DJ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Dominica',
            'country_code' => 'DM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Dominican Republic',
            'country_code' => 'DO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //Countries with E
          [
            'country_name' =>'Ecuador',
            'country_code' => 'EC',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Egypt',
            'country_code' => 'EG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'El Salvador',
            'country_code' => 'SV',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Equatorial Guinea',
            'country_code' => 'GQ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Eritrea',
            'country_code' => 'ER',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Estonia',
            'country_code' => 'EE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Ethiopia',
            'country_code' => 'ET',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with F
          [
            'country_name' =>'Faroe Islands',
            'country_code' => 'FO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Fiji',
            'country_code' => 'FJ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Finland',
            'country_code' => 'FI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'France',
            'country_code' => 'FR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'French Guiana',
            'country_code' => 'GF',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'French Polynesia',
            'country_code' => 'PF',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with G
          [
            'country_name' =>'Gabon',
            'country_code' => 'GA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Gambia',
            'country_code' => 'GM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Georgia',
            'country_code' => 'GE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Germany',
            'country_code' => 'DE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Ghana',
            'country_code' => 'GH',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Gibraltar',
            'country_code' => 'GI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Greece',
            'country_code' => 'GR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Greenland',
            'country_code' => 'GL',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Grenada',
            'country_code' => 'GD',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Guam',
            'country_code' => 'GU',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Guatemala',
            'country_code' => 'GT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Guinea',
            'country_code' => 'GN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Guinea-Bissau',
            'country_code' => 'GW',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Guyana',
            'country_code' => 'GY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with H
          [
            'country_name' =>'Haiti',
            'country_code' => 'HT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Honduras',
            'country_code' => 'HN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Hungary',
            'country_code' => 'HU',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Iceland',
            'country_code' => 'IS',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with I
          [
            'country_name' =>'India',
            'country_code' => 'IN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Indonesia',
            'country_code' => 'ID',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Iran',
            'country_code' => 'IR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Iraq',
            'country_code' => 'IQ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Ireland',
            'country_code' => 'IE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Israel',
            'country_code' => 'IL',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Italy',
            'country_code' => 'IT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with J
          [
            'country_name' =>'Jamaica',
            'country_code' => 'JM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Japan',
            'country_code' => 'JP',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Jordan',
            'country_code' => 'JO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with K
          [
            'country_name' =>'Kenya',
            'country_code' => 'KE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Kiribati',
            'country_code' => 'KI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'North Korea',
            'country_code' => 'KP',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'South Korea',
            'country_code' => 'KR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Kuwait',
            'country_code' => 'KW',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with L
          [
            'country_name' =>'Latvia',
            'country_code' => 'LV',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Lebanon',
            'country_code' => 'LB',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Lesotho',
            'country_code' => 'LS',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Liberia',
            'country_code' => 'LR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Libya',
            'country_code' => 'LY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Lithunia',
            'country_code' => 'LT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with M
          [
            'country_name' =>'Madagascar',
            'country_code' => 'MK',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Malawi',
            'country_code' => 'MW',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Malaysia',
            'country_code' => 'MY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Maldives',
            'country_code' => 'MV',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Mali',
            'country_code' => 'ML',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Malta',
            'country_code' => 'MT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Marshall Islands',
            'country_code' => 'MH',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Martinique',
            'country_code' => 'MQ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Mauritania',
            'country_code' => 'MR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Mauritus',
            'country_code' => 'MU',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Mexico',
            'country_code' => 'MX',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Micronesia',
            'country_code' => 'FM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Moldova',
            'country_code' => 'MD',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Monaco',
            'country_code' => 'MC',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Mongolia',
            'country_code' => 'MN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Montenegro',
            'country_code' => 'ME',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Montserrat',
            'country_code' => 'MS',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Morocco',
            'country_code' => 'MA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Mozambique',
            'country_code' => 'MZ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Myanmar',
            'country_code' => 'MM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with n
          [
            'country_name' =>'Namibia',
            'country_code' => 'NA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Nauru',
            'country_code' => 'NR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Nepal',
            'country_code' => 'NP',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Netherlands',
            'country_code' => 'NL',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Netherlands Antilles',
            'country_code' => 'AN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'New Caledonia',
            'country_code' => 'NC',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'New Zealand',
            'country_code' => 'NZ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Nicaragua',
            'country_code' => 'NI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Niger',
            'country_code' => 'NE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Nigeria',
            'country_code' => 'NG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Norfolk Island',
            'country_code' => 'NF',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Northern Mariana Islands',
            'country_code' => 'MP',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Norway',
            'country_code' => 'NO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //country with O
          [
            'country_name' =>'Oman',
            'country_code' => 'OM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with P
          [
            'country_name' =>'Pakistan',
            'country_code' => 'PK',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Palau',
            'country_code' => 'PW',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Panama',
            'country_code' => 'PS',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Papua New Guinea',
            'country_code' => 'PG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Paraguay',
            'country_code' => 'PY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Peru',
            'country_code' => 'PE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Philippines',
            'country_code' => 'PH',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Poland',
            'country_code' => 'PL',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Portugal',
            'country_code' => 'PT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Puerto Rico',
            'country_code' => 'PR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with Q
          [
            'country_name' =>'Qatar',
            'country_code' => 'QA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with R
          [
            'country_name' =>'Reunion',
            'country_code' => 'RE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Romania',
            'country_code' => 'RO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Russia',
            'country_code' => 'RU',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with S
          [
            'country_name' =>'Saint Kitts and Nevis',
            'country_code' => 'KN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Saint Lucia',
            'country_code' => 'LC',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Saint Vicent and Grenadines',
            'country_code' => 'VC',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Samoa',
            'country_code' => 'WS',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Sao Tome and Principe',
            'country_code' => 'ST',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Saudi Arabia',
            'country_code' => 'SA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Senegal',
            'country_code' => 'SN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Serbia',
            'country_code' => 'RS',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Seychelles',
            'country_code' => 'SC',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Sierra Leone',
            'country_code' => 'SL',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Singapore',
            'country_code' => 'SG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Slovakia',
            'country_code' => 'SK',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Slovenia',
            'country_code' => 'SI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Solomon Islands',
            'country_code' => 'SB',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Somalia',
            'country_code' => 'SO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'South Africa',
            'country_code' => 'ZA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Spain',
            'country_code' => 'ES',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Sri Lanka',
            'country_code' => 'LK',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Sudan',
            'country_code' => 'SD',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Suriname',
            'country_code' => 'SR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Svalbard and Jan Mayen Islands',
            'country_code' => 'SJ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Sweden',
            'country_code' => 'SE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Switzerland',
            'country_code' => 'CH',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Syria',
            'country_code' => 'SY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with T
          [
            'country_name' =>'Taiwan',
            'country_code' => 'TW',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Tanzania',
            'country_code' => 'TZ',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Thailand',
            'country_code' => 'TH',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Togo',
            'country_code' => 'TG',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Tonga',
            'country_code' => 'TO',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Trinidad and Tobago',
            'country_code' => 'TT',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Tunisia',
            'country_code' => 'TN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Turkey',
            'country_code' => 'TR',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Turkmenistan',
            'country_code' => 'TM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Turks and Caicos Islands',
            'country_code' => 'TC',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Tuvalu',
            'country_code' => 'TV',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with U
          [
            'country_name' =>'Ukraine',
            'country_code' => 'UA',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'United Arab Emirates',
            'country_code' => 'AE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'United Kingdom',
            'country_code' => 'GB',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'United States of America',
            'country_code' => 'US',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Uruguay',
            'country_code' => 'UY',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with V
          [
            'country_name' =>'Vanuatu',
            'country_code' => 'VU',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Venezuela',
            'country_code' => 'VE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Viet Nam',
            'country_code' => 'VN',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Virgin Islands US',
            'country_code' => 'VI',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          //countries with Y-Z
          [
            'country_name' =>'Yemen',
            'country_code' => 'YE',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Zambia',
            'country_code' => 'ZM',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
          [
            'country_name' =>'Simbabwe',
            'country_code' => 'ZW',
            'cordinates' => 'test',
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
          ],
        ];


        DB::table('countries')->insert($countries);

        $this->enableForeignKeys();
    }
}
